# Generated by Django 4.1.2 on 2022-10-22 23:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Cliente',
        ),
    ]
