# Generated by Django 4.1.2 on 2022-11-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_categoria_estado_genero_perfiles_usersmetadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
