# Generated by Django 4.1.2 on 2022-11-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cliente_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
